name: Prune Packages
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # every day at midnight, utc

jobs:
  delete-package-versions:
    permissions:
      contents: read
      packages: write
    name: Prune Packages
    runs-on: ubuntu-latest
    steps:
      - uses: snok/container-retention-policy@v3.0.0
        with:
          account: codekow
          token: ${{ secrets.GITHUB_TOKEN }}
          image-names: "tor"
          tag-selection: untagged
          keep-n-most-recent: 3
          dry-run: "true"
