name: Prune Packages
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # every day at midnight, utc

jobs:
  delete-package-versions:
    permissions:
      contents: read
      packages: write
    name: Prune Packages
    runs-on: ubuntu-latest
    steps:
      - uses: snok/container-retention-policy@v3.0.1
        with:
          account: user
          token: ${{ secrets.GITHUB_TOKEN }}
          cut-off: 5h
          image-names: "tor"
          tag-selection: both
          keep-n-most-recent: 5
          # dry-run: "true"
